# Config format schema number
format_version: 1

###################
## Dataset options
dataset_params:
  training_size: 28130
  dataset_type: "point_image_dataset_nus"
  pc_dataset_type: "nuScenes"
  collate_type: "collate_fn_default"
  ignore_label: 0
  num_classes: 17
  label_mapping: "/userHome/xzy/Projects/elon/Scatter-annotation/config/label_mapping_nuscenes.yaml"

  data_loader:
    data_path: "/data/xzy/elon/nuscenes/"
    shuffle: False
    num_workers: 1
    batch_size: 1
   
target_label:
  - []
  - [11,15,7,16,14]                      # 'barrier' 1
  - [11,15]                              # 'bicycle' 2
  - [11,13,7,15,10,4]                    # 'bus' 3
  - [11,7,16,14,12,15,7,10,3,6,13,9,12]  # 'car' 4
  - [11,13,7,15,4]                       # 'construction_vehicle' 5
  - [11,7,4,13]                          # 'motorcycle' 6
  - [11,4,15,16,14,8,10,1]               # 'pedestrian' 7
  - [11,7,13,16,14,15,4]                 # 'traffic_cone' 8
  - [11,15,10,16,4]                      # 'trailer' 9
  - [11,15,4,9,3,13,15,16,7,14]          # 'truck' 10
  - [4,8,15,16,14,13,12,7]               # 'driveable_surface' 11
  - [11,4,15,14,13]                      # 'other_flat' 12
  - [11,15,8,14,16,4,12,10,6]            # 'sidewalk' 13
  - [11,16,7,15,4,13,12,10,1]            # 'terrain' 14
  - [11,16,7,14,13,12,4,10,3,2,8,5,1]    # 'manmade' 15
  - [11,15,14,7,4,13,1]                  # 'vegetation' 16

colorMap: 
  - [0, 0, 0]           # 0 'noise'
  - [255, 120, 50]      # 1 'barrier'
  - [100, 230, 245]     # 2  'bicycle'
  - [135, 60, 0]        # 3  'bus'
  - [100, 150, 245]     # 4  'car'
  - [100, 80, 250]      # 5  'construction_vehicle'
  - [30, 60, 150]       # 6  'motorcycle'
  - [255, 30, 30]       # 7  'pedestrian'
  - [255, 0, 0]         # 8  'traffic_cone'
  - [255, 240, 150]     # 9  'trailer'
  - [80, 30, 180]       # 10 'truck'
  - [255, 0, 255]       # 11 'driveable_surface'
  - [175, 0, 75]        # 12 'other_flat'
  - [75, 0, 75]         # 13 'sidewalk'
  - [150, 240, 80]      # 14 'terrain'
  - [255, 200, 0]       # 15 'manmade'
  - [0, 175, 0]         # 16  'vegetation'
            