# Config format schema number
format_version: 1

###################
## Dataset options
dataset_params:
  dataset_type: "point_image_dataset_semkitti"
  pc_dataset_type: "SemanticKITTI"
  collate_type: "collate_fn_default"
  num_classes: 20
  ignore_label: 0
  label_mapping: "/userHome/xzy/Projects/elon/Scatter-annotation/config/label_mapping_kitti.yaml"


  data_loader:
    data_path: "/data/xzy/elon/JS3CNet/semantic_kitti/sequences/"
    shuffle: False
    num_workers: 1
    batch_size: 1
    
target_label:
  - []
  - [9,12,13,2,19,16,14,11,15,18,4,5,17,7,3,10] # 1:"car" 
  - [9,3,1,11,15,4,5,17,18]                     # 2:"bicycle" 
  - [9,13,1]                                    # 3:"motorcycle" 
  - [9,15,1,14,11,1,15,17,2,10]                 # 4:"truck" 
  - [9,12,1,14,15,17,2,10]                      # 5:"other-vehicle" 
  - [9, 14,1, 15, 13,8,17,11]                   # 6:"person" 
  - [9, 14, 1,15]                               # 7:"bicyclist" 
  - [9, 14, 1,15,6]                             # 8:"motorcyclist" 
  - [11, 12, 1,10,17,14]                        # 9:"road" 
  - [9, 11,1,13, 14,15,17,4,5]                  # 10:"parking" 
  - [9,14,17,12,10,4,1,15,6]                    # 11:"sidewalk" 
  - [9,11,17,15,17]                             # 12:"other-ground" 
  - [9.14,1,15,18,19]                           # 13:"building" 
  - [13,11,15,4,16,17,18,1,9,19,5]              # 14:"fence" 
  - [1,14,4,17,19,13,16,12,2,11]                # 15:"vegetation" 
  - [15,14,1]                                   # 16:trunk" 
  - [9,15,1,12,10,14,11,2,5,4,6]                # 17:"terrain" 
  - [9,15,17,19,14,13,1,2]                      # 18:"pole"
  - [9,15,18,1,14,13]                           # 19:"traffic-sign"


colorMap: 
  - [0, 0, 0]          # 0 "unlabeled"
  - [100, 150, 245]    # 1 "car"
  - [100, 230, 245]    # 2 "bicycle"
  - [30, 60, 150]      # 3 "motorcycle"
  - [80, 30, 180]      # 4 "truck"
  - [100, 80, 250]     # 5 "other-vehicle"
  - [255, 30, 30]      # 6 "person"
  - [255, 40, 200]     # 7 "bicyclist"
  - [150, 30, 90]      # 8 "motorcyclist"
  - [255, 0, 255]      # 9 "road"
  - [255, 150, 255]    # 10 "parking"
  - [75, 0, 75]        # 11 "sidewalk"
  - [175, 0, 75]       # 12 "other-ground"
  - [255, 200, 0]      # 13 "building"
  - [255, 120, 50]     # 14 "fence"
  - [0, 175, 0]        # 15 "vegetation"
  - [135, 60, 0]       # 16 "trunk"
  - [150, 240, 80]     # 17 "terrain"
  - [255, 240, 150]    # 18 "pole"
  - [255, 0, 0]        # 19 "traffic-sign"




# colorMap: [ [0, 0, 0],          # 0 "unlabeled", and others ignored 
#             [100, 150, 245],    # 1 "car" 
#             [100, 230, 245],    # 2 "bicycle" 
#             [30, 60, 150],      # 3 "motorcycle" 
#             [80, 30, 180],      # 4 "truck" 
#             [100, 80, 250],     # 5 "other-vehicle" 
#             [255, 30, 30],      # 6 "person" 
#             [255,40,200],       # 7 "bicyclist" 
#             [150, 30, 90],      # 8 "motorcyclist" 
#             [255, 0, 255],      # 9 "road" 
#             [255, 150, 255],    # 10 "parking" 
#             [75, 0, 75],        # 11 "sidewalk"
#             [175, 0, 75],       # 12 "other-ground" 
#             [255, 200, 0],      # 13 "building"
#             [255, 120, 50],     # 14 "fence" 
#             [0, 175, 0],        # 15 "vegetation" 
#             [135, 60, 0],       # 16 "trunk" 
#             [150, 240, 80],     # 17 "terrain" 
#             [255, 240, 150],    # 18 "pole"
#             [255, 0, 0]         # 19 "traffic-sign" 
#             ]